language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: MycSwUC82Cd+NAu/SPfwNEWnia41vowyWZz//XmlzPnBZzECBizcuD8VtY4VTWpHu6+fa3nnwOg1yBsfFHadKNdrO5gbIZreZ4FGUYk/vqNxUv7d+i+UxG2M+Y6Fnlqsn2ojfVdWACWyOMOfw56+xEMEvvnKDAyKBJOB3a8laJ7eDUJZH+scfHHFgzKZ2UWONUaHdydJrIqpIQfw2C5l9eus97sh1eI4S64T6L165NS/VpB8mZ78Gh912dkt6Uk5mFn2hJIMdFOzuzrxz2GOBMxnV8PoFV86GDL7/NH/smKAfaNZaKKLdTvRRyVeeQsSqPtxOS4WZQDiRyql5nTR8OAQcE2ZOErsouaGVbFJ8Jn4f5ZrSuSOUORbnAJeY0itAldju+e0H14STrPfLkqq1fan7tWKKvmd+DqUSjv6AN7W3dFru/H8kuh3dilUvFXUcFazxHzeB+Tt8WDyKnXxkrG5mtqgj1Kp+MQBELZMcRjV76GncbtH+h1Cys3UvnrwHvD53xRV7RhH02DegzxOemF4NKR3ckDbdJqh03i6JmQp3K5NCVCg7KAlRoVdy/jdRdgi22lEJWB82sKBWZ7UibOFLQ60Tlx8bm6lnLYMFqG9EMxigEbYcYlSXDoli6lhrQRBlJU68+TIA3ZVPpPaBumUGF63a9NztokqAd6bGNI=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global: 
  - secure: LXAZ4Nqqoh/IeRpPMelt1ao5LzKu1nwmezw1Y0UcSk5GL0XGQJ0rOOaWEvtqefhBy9dnuZp9k5Rc9b/v68gfSqDO+tUrdv2ahu6WGgoPHwC4HJXKIZGmtEz6uHl+7gcd+9a5NK9PikhDkFaIuUMlhaEg/S79W4avQprh1y3kXMmu8jft3h6MeaNPmpLC/mACBH+hQ1a15nYpkGwUXYRPGwff6HfZzA+0FOtQdEFifK/Tu+zHH8RtagZcaHE6ONCESIGZzT3wU5Ak2eIWXUtKS6ssgZYlJmpHUfyPV65NX5EtHa8XrUPQ/xuTftXwpbGbg0qMWFa9PE8yOu1dU8Z+ef6h3/BxjVd0HdFoV2j+ynHKlnhuWK35pNyIynq63AP3VXf9LzvFxeVbYbaRaWHJC9eu98xAa24NFUUUVIDIpI1eMH+6nCmDudyhdQxuYyZx/iYsdtmk5A+LoaReSsVR9UIeok5iTNBI8Xtut9J50grbw+fe8/BhoMe8G/v2y63WqazXkVBsAX0YL5fFwEeoIFyhRQqlHxlYyYGL9EbeLZmMUp84FKHDIHnjiea4H19Yl1hwyLXbmO5Z5udDAM1Fcppi1QPAh9MZkXEbQptPWQceP67MlXIPw1BCz46zC9xGHB/BqlssJpMjKmNrtv/VUZQ/RRIcOxYuOTC+38hiLfM=
  - secure: USAI3BcFdbZeAtLBtNbzFK9dMzNAybG70T1hC3j9GkmoCyRoBmRnKIepqsHjnEGNL1O7271zDRlocbozDTrX3Pk1Cs8IBQuZDoRiNV3ZRFQ+pOdEAQEPXheyarakWqU527sGopeZuCTJt7EmfWDzFh1Seg1CFyZ8epij83J9yZWhUy4zMmTzMR0F5UPc3o27dpUCxZepnHnWrphAe2jiz5bo7tR8diPoMedkCdrvVgTcy0J7UTsLZboFVqbMbY6wTxY/t5XpPIzdlgZmtxzxLoTSODWg+Z+C8EoazBnOOa1vTxpl+Ey0IdoHuqpok251tlolz1CF5zWzQzdowpZkInLvJB1JI4v/slYi0wo2e1GmsSftvm9wIJ4IiycHOOPmb6ZT2hxJ/o5q7F87UwDSDcH8fvKhLTTinHv8S+m/0xogY1dkxjMCd305+tO9GWQ7nszFS9HfRH6GIcOdaiMead6usSlHehJPcX1pBU9dfe2DVgc7+h+RLnyJtgBUD4+Xs4KfURM+TdyE4Whrs+od60TT1T4xOpm9vUUiBN00eD/GW52tDX01DQflK5Bel+YZaPuIdkLmcx3RaVP0UDlBrFb72MD6NGIWvt+nygyCM1sX3fnQS2SOXVDoJ7KRIyxF70h+AAxSnXdGm0TEl8igxNmeXszmgqH1cp3KefXSTYI=
  matrix:
  - SCC_DOCKER_IMAGE=anthonydenecheau/scc-dog-daemon:version1.0
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push $SCC_DOCKER_IMAGE
