#Default port is 8083
server:
  port: 8083
  
spring:
#Kafka settings
  cloud:
    stream:
      bindings:
        outboundDogChanges:
            destination:  dogOdsTopic
            content-type: application/json
        outboundOwnerChanges:
            destination:  ownerOdsTopic
            content-type: application/json
        outboundBreederChanges:
            destination:  breederOdsTopic
            content-type: application/json
        outboundTitleChanges:
            destination:  titleOdsTopic
            content-type: application/json
        outboundPedigreeChanges:
            destination:  pedigreeOdsTopic
            content-type: application/json
        outboundParentChanges:
            destination:  parentOdsTopic
            content-type: application/json
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
          autoCreateTopics: true
  
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.scc: DEBUG      
    
